apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitclientapp
  name: gitclientapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitclientapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitclientapp
    spec:
      containers:
      - image: vinays8118/gitclient:30
        name: gitclient
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitclientapp
  name: gitclientsvc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8888
  selector:
    app: gitclientapp
  type: LoadBalancer
